apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: gcp-vm-stop
  namespace: default
spec:
  # We are working inside GCP and might not have a Kubernetes application at hand.
  annotationCheck: "false"

  engineState: active
  auxiliaryAppInfo: ""
  chaosServiceAccount: gcp-vm-stop-sa
  experiments:
    - name: gcp-vm-stop
      spec:
        components:
          env:
            # Google application credentials file.
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/gcp/key.json
            # The virtual machine instance to stop.
            - name: GCP_INSTANCE
              value: "<my-instance>"
            # The virtual machine instances project.
            - name: GCP_PROJECT
              value: "<my-project>"
            # The virtual machine instances zone.
            - name: GCP_ZONE
              value: "<my-zone>"
          secrets:
            - name: gcp-vm-stop
              mountPath: /var/gcp
