apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  # annotations:
  #   cnrm.cloud.google.com/project-id: <patched>
  name: gcp-vm-stop
  namespace: default
spec:
  description: Provide GCP access to stop virtual machine instances
  displayName: gcp-vm-stop
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: gcp-vm-stop
  namespace: default
spec:
  serviceAccountRef:
    name: gcp-vm-stop
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gcp-vm-stop-compute-instance-admin
  namespace: default
spec:
  memberFrom:
    serviceAccountRef:
      name: gcp-vm-stop
  role: roles/compute.instanceAdmin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    # external: projects/<patched>
