apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: gcp-vm-restart
  version: 0.1.0
  annotations:
    categories: gcp
spec:
  displayName: gcp-vm-restart
  categoryDescription: |
    Restart a virtual machine instance. Additionally a IAM service account is required.
  keywords:
    - "gcp"
    - "vm"
    - "restart"
  platforms:
    - "GCP"
  maturity: alpha
  maintainers:
    - name: Julian Nodorp
      email: jnodorp@jaconi.io
  minKubeVersion: 1.12.0
  provider:
    name: jaconi
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: latest
  links:
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/getstarted/
  icon:
    - url: https://raw.githubusercontent.com/jaconi-io/litmus/main/charts/gcp/icons/gcp-vm-restart.png
      mediatype: image/png
  chaosexpcrdlink: https://raw.githubusercontent.com/jaconi-io/litmus/main/charts/gcp/gcp-vm-restart/experiment.yaml
