apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: ~
  name: gcp-vm-restart
spec:
  description: Provide GCP access to restart virtual machine instances
  displayName: gcp-vm-restart
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: gcp-vm-restart
spec:
  serviceAccountRef:
    name: gcp-vm-restart
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gcp-vm-restart-compute-instance-admin
spec:
  memberFrom:
    serviceAccountRef:
      name: gcp-vm-restart
  role: roles/compute.instanceAdmin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: ~
